---
Name: silverstripe-frontdesk-kit-routes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'profile//$Action/$ID': 'Atwx\SilverstripeFrontdeskKit\Controller\ProfileController'
    'users//$Action/$ID':   'Atwx\SilverstripeFrontdeskKit\Controller\UserManageController'
    'groups//$Action/$ID':  'Atwx\SilverstripeFrontdeskKit\Controller\GroupManageController'
